config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/about", to: "static_pages#about"

  get "/bmi", to: "static_pages#bmi"
  post "/bmi", to: "static_pages#bmi"

  resources :contacts, only: [:index, :create]
  resources :posts

  namespace :admin do
    resources :contacts, except:[:new, :create, :destroy]
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :subject, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      # 成功
      flash[:notice] = "已成功送出!"

      # send mail
      ContactMailer.send_notification(@contact).deliver_now

      redirect_to contacts_path
    else
      # 失敗
      flash[:notice] = "失敗!!"
      render action: :index
    end
  end

  # Strong Parameter
  private
  def contact_params
    params.require(:contact).permit(:subject, :email, :content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only:[:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.save
    flash[:notice] = "已成功送出!"
    redirect_to root_path
  end

  def edit
  end

  def update
    # do update
  end

  def show
  end

  def destroy
    # do delete
  end

  # Strong Parameter
  private
  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = Post.find_by(id: params[:id])
    redirect_to posts_path unless @post
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

  def bmi
    if request.post?
      h = params[:height].to_f / 100
      w = params[:weight].to_f
      @bmi = w / (h * h)
    end
  end

end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def taiwan_no1_calendar(the_date)
    content_tag :span do
      "民國 #{the_date.year - 1911} 年 #{the_date.month} 月 #{the_date.day} 日"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/contacts/index.html.erb
<h1>聯絡清單</h1>

<ul>
<% @contacts.each do |contact| %>
  <li>
  <%= link_to contact.subject, admin_contact_path(contact) %>
  <%= link_to '編輯', edit_admin_contact_path(contact) %>
  <%= link_to '刪除', admin_contact_path(contact), method: 'delete'%>
  </li>
<% end %>
</ul>

app/views/contacts/index.html.erb
<% provide :title_block, "Contact Us" %>

<h1>聯絡我們</h1>

<% if @contact.errors.any? %>
  <ul>
  <% @contact.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= simple_form_for(@contact) do |f| %>
  <%= f.input :subject %>
  <%= f.input :email %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HandcraftDemo - <%= yield :title_block %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] %>
<%= yield %>

<%= yield :bottom_js %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/posts/_post.html.erb
<li>
  <%= post.title %>
  <%= link_to '檢視', post %>
  <%= link_to '編輯', edit_post_path(post) %>
  <%= link_to '刪除', post_path(post), method: "delete" %>
</li>

app/views/posts/_post_list.html.erb
<ul>
  <% posts.each do |post| %>
    <li>
    <%= post.title %>
    <%= taiwan_no1_calendar(post.created_at) %>
    <%= link_to '檢視', post %>
    <%= link_to '編輯', edit_post_path(post) %>
    <%= link_to '刪除', post_path(post), method: "delete" %>
    </li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>

<%= link_to '新增', new_post_path %>

<%= render "post_list", posts: @posts %>

<% content_for :title_block do %>
12345
<% end %>
<% provide :bottom_js, "hello, ruby" %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/bmi.html.erb
<h1>BMI 計算器</h1>

<%= form_tag('/bmi', method:"post") do %>
  身高：<%= text_field_tag :height %><br />
  體重：<%= text_field_tag :weight %><br />
  <%= submit_tag "計算" %>
<% end %>

<% if @bmi %>
<hr />
BMI = <%= @bmi.round(2) %>
<% end %>

app/views/static_pages/home.html.erb
<h1>Home</h1>